# Generated by Django 3.2.7 on 2024-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_document',
            name='doc_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_text',
            name='text_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
